"""
Contains type casting functions for each config variable.
"""

CONFIG_SCHEMA = {
    "lag": int,
    "fib_factor": float,
    "timeframe": str,
    "target_coeff": float,
    "stoploss_coeff": float,
    "target_setup_function": str,
    "stoploss_setup_function": str,
    "min_block_height_percentage": float,
    "max_block_height_percentage": float,
    "usdt_per_trade": float,
    "leverage": float,
    "leverage_type": str,
    "startup_n_days": int,
    "calc_interval": float,
    "binance_ws_endpoint": str,
    "telegram_api_endpoint": str,
    "live_sim_tick_interval": float,
    "binance_cache_retry_interval": float,
    "binance_cache_max_retries": int,
    "binance_cache_resync_buffer": int,
    "telegram_api_max_retries": int,
    "telegram_api_base_retry_interval": float,
    "telegram_api_send_message_delay": float,
    "ws_error_retry_interval": int,
    "ws_error_max_retries": int,
    "validation": bool,
    "signal_proximity_check": bool,
    "signal_proximity_check_percent": int,
    "chart_data_write_interval": float,
    "proxy_server": str,
    "dev": bool,
    "TG_BOT_AUTH_TOKEN": str,
    "TG_DEV_CHANNEL_ID": str,
    "TG_PROD_CHANNEL_ID": str,
    "clear_logs": bool,
    "clear_state": bool,
    "clear_klines": bool,
    "dry": bool,
    "clean": bool,
    "symbols_filename": str,
    "direction": str,
    "cid": str,
}
